spring.application.name=gerenciamento-ocorrencias
server.port=8083


# Configurações do PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/gerenciamento_ocorrencias
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Adicionar estas linhas
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
